# Generated by Django 5.0.6 on 2024-08-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olchauz', '0002_alter_category_image_alter_group_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/group/'),
        ),
    ]
