# Generated by Django 5.0.6 on 2024-08-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olchauz', '0003_alter_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='value',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
